# SERVQUAL LLM Configuration
# Validated settings based on testing results: 71% reliability, 5.5s processing time

llm_settings:
  model_name: "mistral:7b"
  ollama_url: "http://localhost:11434"
  timeout: 20                    # 20 second maximum (6s target + buffer)
  temperature: 0.1               # Low for consistency
  top_p: 0.3                    # Focused generation
  max_tokens: 120               # Minimal for JSON output
  stop_sequences: ["\n", "```", "Based on"]

# Validated performance targets from testing
performance_targets:
  max_processing_time_ms: 6000     # 6 seconds per review maximum
  min_success_rate: 0.99           # 99% minimum success rate
  target_throughput: 0.18          # 0.18 reviews per second
  max_memory_usage_mb: 2048        # 2GB maximum memory usage

# Validated detection thresholds (achieved in testing)
detection_thresholds:
  reliability_min: 0.70            # 71% achieved in testing
  assurance_min: 0.55              # 57.5% achieved
  tangibles_min: 0.55              # 58.5% achieved
  empathy_min: 0.15                # 15.5% achieved
  responsiveness_min: 0.30         # 33.5% achieved

# Platform-specific configurations
platform_support:
  amazon:
    priority_dimensions: ["reliability", "responsiveness"]
    context_keywords: ["prime", "fulfillment", "delivery"]
  ebay:
    priority_dimensions: ["assurance", "reliability"]
    context_keywords: ["seller", "auction", "feedback"]
  etsy:
    priority_dimensions: ["tangibles", "empathy"]
    context_keywords: ["handmade", "vintage", "artisan"]
  temu:
    priority_dimensions: ["assurance", "responsiveness"]
    context_keywords: ["value", "bulk", "fast delivery"]
  shein:
    priority_dimensions: ["tangibles", "responsiveness"]
    context_keywords: ["fashion", "trendy", "size chart"]

# Rating-aware analysis configuration
rating_analysis:
  low_rating_threshold: 2          # Ratings <= 2 (80% issue detection target)
  high_rating_threshold: 4         # Ratings >= 4 (36% issue detection target)
  sentiment_scaling:
    low_rating_boost: -0.3         # Boost negative sentiment for low ratings
    high_rating_boost: 0.3         # Boost positive sentiment for high ratings
    neutral_rating_factor: 0.1     # Minimal adjustment for rating 3

# Fallback configuration for 100% success rate
fallback_settings:
  enable_keyword_fallback: true
  fallback_confidence: 0.75        # Lower confidence for fallback results
  keyword_match_threshold: 1       # Minimum keyword matches for relevance

# Batch processing configuration
batch_processing:
  default_batch_size: 25           # Reviews per batch
  progress_log_interval: 10        # Log every 10 reviews
  memory_cleanup_interval: 50      # Clear cache every 50 reviews
  max_retries: 2                   # Retry failed requests
  retry_delay_ms: 1000            # 1 second delay between retries

# Integration settings
integration:
  storage_table: "servqual_scores"
  model_version_prefix: "mistral-7b"
  enable_fallback_logging: true
  performance_monitoring: true
  cache_responses: false           # Disable caching for production